# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:39
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('bookmark', '0003_userbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmark',
            name='tag',
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
