# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20171120_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bookmark.Tag'),
        ),
    ]
