# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_auto_20171124_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmark',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
