# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20171124_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bookmark.Tag'),
        ),
    ]
